### ISSUE TITLE
Build error - The type JSIStudios.SimpleRESTServices.Client.IRestService' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by cliffordru** [openstacknetsdk/openstack.net#492] opened 2015-04-22 18:24 UTC
I am getting the build error: 
The type 'JSIStudios.SimpleRESTServices.Client.IRestService' is defined in an assembly that is not referenced. You must add a reference to assembly 'SimpleRESTServices, Version=1.3.0.0, Culture=neutral, PublicKeyToken=8965cea5c205d3a3'.	

Steps to reproduce:
1. Create a new project in Visual Studio
2. Using NuGet package manager, installed openstack.net (and dependencies)
3. Added sample code (https://developer.rackspace.com/sdks/dot-net/) to create CloudIdentity and CloudProvider
4. Get the error above on this line:
CloudIdentityProvider cloudIdentityProvider = new CloudIdentityProvider(cloudIdentity);

I verified that SimpleRestServices was installed by NuGet and is referenced - location - \packages\SimpleRESTServices.1.3.0.2\lib\net40\SimpleRESTServices.dll

Can you please assist with troubleshooting?

Thanks

**Comment by DonSchenck** [comment] 2015-04-22 19:05
Clifford --

Do you have the following "using" statement in your code?:

```
using net.openstack.Core.Domain;
```

It appears as though this is missing from the sample code you found.

**Comment by cliffordru** [comment] 2015-04-22 19:37
Hi Don, thank you for your reply.  Yes, I have the following using statements:

using net.openstack.Core.Domain;
using net.openstack.Providers.Rackspace;

**Comment by sharwell** [comment] 2015-04-22 19:53
Hi @cliffordru,

I'm sorry to hear you are facing these difficulties (and thank you for taking the time to report them).

### Workaround

You can work around this issue immediately by installing SimpleRESTServices 1.3.0.1, instead of 1.3.0.2.

### Cause

The root cause of this problem is JSIStudios/SimpleRestServices#64, which changed the strong name key used for the SimpleRESTServices build (this was a terrible move on my part).

### Solution

I need to update the build to use the original key, and release SimpleRESTServices 1.3.0.3. This would allow users of SimpleRESTServices 1.3.0.1 (the version declared in openstack.net) to upgrade to the latest release of SimpleRESTServices without breaking their code. The SimpleRESTServices 1.3.0.2 release would remain broken, but since the openstack.net project does not directly refer to it, future users would not get stuck in the position you are in.

**Comment by DonSchenck** [comment] 2015-04-22 20:05
What's odd is that when I use Nuget to install openstack.net, it defaults to SimpleRESTServices 1.3.0.1.

??

**Comment by cliffordru** [comment] 2015-04-22 20:08
That is interesting...for me it referenced SimpleRESTServices.1.3.0.2.  Perhaps due to my project targeting 4.5.1?

I will try your workaround shortly and let you know how it goes

**Comment by sharwell** [comment] 2015-04-22 20:09
There may be a command line flag (for the Package Manager Console window) which tells NuGet to use the latest version of dependencies instead of the declared version. Visual Studio 2015 goes further and exposes this option in the UI. Either way, all users would see SimpleRESTServices appear in the Upgrade tab of the NuGet UI, and nothing would stop them from upgrading (but then it breaks...).

I'm closing this because openstack.net declares the correct dependency already, so all that's left is addressing the strong name problem on the other project (I opened JSIStudios/SimpleRestServices#66 for that).

**Closed by sharwell** 2015-04-22 20:09 UTC
Labels: bug, v1
