### ISSUE TITLE
Add supportion for keystone v3 version

### ISSUE THREAD

**Issue by jiangzehua** [openstacknetsdk/openstack.net#607] opened 2016-03-25 10:46 UTC
Keystone api is version 3.6 now, but opesnstack.net only support v2.0. We should enhance supportion for identity.

**Comment by carolynvs** [comment] 2016-03-25 13:34
Hi @jiangzehua, I am closing this issue as a duplicate of #503. It is definitely on our roadmap! :smile:

**Closed by carolynvs** 2016-03-25 13:34 UTC
