### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by DonSchenck** [openstacknetsdk/openstack.net#506] opened 2015-06-08 14:54 UTC
I ran the .\build.ps1 script on my Windows 8.1 machine and received one error:

"C:\Users\User\Documents\GitHub\openstack.net\src\OpenStack.Net\OpenStack.Net.netcore45.csproj" (Rebuild target) (13) ->
(_GetAppxManifestSchemaItems target) ->
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(598,9): error APPX3213: SDK folder containing 'Windows.props' for
 'Windows 8.0' cannot be located. See http://go.microsoft.com/fwlink/?prd=12560&pver=1.0&plcid=0x409&ar=MSDN&sar=PlatformMultiTargeting&o1=Windows&o2=8.0 for more inform
ation. [C:\Users\User\Documents\GitHub\openstack.net\src\OpenStack.Net\OpenStack.Net.netcore45.csproj]

**Comment by sharwell** [comment] 2015-06-08 19:00
This problem was caused by not having the [Windows Software Development Kit (SDK) for Windows 8](https://msdn.microsoft.com/en-us/windows/desktop/hh852363.aspx) installed. This SDK is automatically installed with some, but not all versions of Visual Studio, so you only need to download and install it manually if the build is failing with this error.

:memo: Note that some users may need to deselect the "Application Verifier" in the installer, but that component is not required for building this project.

**Comment by carolynvs** [comment] 2015-06-24 12:51
Fixed by #513

**Closed by carolynvs** 2015-06-24 12:51 UTC
Labels: question
